# Generated by Django 5.2.4 on 2025-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
    ]
